table Milestones
	lineageTag: 934cc277-d89f-4a28-a9eb-c9e4ce1f1822

	column Activity
		dataType: string
		lineageTag: e2f6381f-d242-4f1d-b3db-11ae2dfbf6ad
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Milestone Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6886b112-6370-4709-980b-2f2cd24781e4
		summarizeBy: none
		sourceColumn: Milestone Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Milestone Type'
		dataType: string
		lineageTag: c0e13bf6-b313-4712-8577-06905eb55395
		summarizeBy: none
		sourceColumn: Milestone Type

		annotation SummarizationSetBy = Automatic

	column 'Milestone Label'
		dataType: string
		lineageTag: 081280e1-7cdf-4b97-9522-b3c7f6428866
		summarizeBy: none
		sourceColumn: Milestone Label

		annotation SummarizationSetBy = Automatic

	column 'Label Position'
		dataType: string
		lineageTag: 27731100-29cc-462b-8795-fc1634f59089
		summarizeBy: none
		sourceColumn: Label Position

		annotation SummarizationSetBy = Automatic

	column 'Milestone Note'
		dataType: string
		lineageTag: c3a9d712-6f4e-4d8b-a52e-1b9c8e3f7d04
		summarizeBy: none
		sourceColumn: Milestone Note

		annotation SummarizationSetBy = Automatic

	partition Milestones-8f2a6180-e056-4455-80c8-0e3d1e0f0a5e = m
		mode: import
		source =
				let
				    /*
				     * DEMO DATA — embedded inline so the visual renders on any clone
				     * with zero setup (no file path, no internet dependency).
				     *
				     * To switch this query to an Excel workbook (so you can edit the
				     * data in Excel instead of editing M code here), comment out the
				     * `Source = #table(...)` step below and uncomment the EXCEL SOURCE
				     * block. Update YOUR_FILE_PATH to your local xlsx.
				     */
				    Source = #table(
				        type table [Activity = text, Milestone Date = date, Milestone Type = text, Milestone Label = nullable text, Label Position = text, Milestone Note = nullable text],
				        {
				            {"Line 3 Automation", #date(2026, 2, 15), "Major", "Cell design review", "R", null},
				            {"Line 3 Automation", #date(2026, 3, 10), "Minor", "Equipment delivered", "L", null},
				            {"Line 3 Automation", #date(2026, 3, 28), "Major", "Line live", "R", null},
				            {"Plant 2 Expansion", #date(2026, 1, 15), "Minor", "Groundbreaking", "R", null},
				            {"Plant 2 Expansion", #date(2026, 5, 20), "Major", "Foundation poured", "R", "Concrete pour delayed 3 days due to weather; on critical path."},
				            {"Plant 2 Expansion", #date(2026, 9, 15), "Major", "Equipment installed", "R", "Two CNC mills arriving Q3 from Yamazaki; install crew booked."},
				            {"Plant 2 Expansion", #date(2026, 12, 20), "Minor", "Commissioning", "L", null},
				            {"MES Pipeline Refresh", #date(2026, 2, 28), "Minor", "Schema lock", "R", null},
				            {"MES Pipeline Refresh", #date(2026, 6, 15), "Major", "MES cutover", "R", "Cutover plan reviewed with operations; rollback path documented."},
				            {"MES Pipeline Refresh", #date(2026, 11, 30), "Major", "Legacy SCADA off", "L", null},
				            {"Mobile Operator Console", #date(2026, 9, 10), "Minor", "Pilot floor rollout", "R", null},
				            {"Mobile Operator Console", #date(2026, 12, 1), "Major", "Full deployment", "R", "Hardware refresh (Zebra TC52) ordered alongside software rollout."},
				            {"Mobile Operator Console", #date(2027, 4, 20), "Major", "Adoption target met", "R", null},
				            {"Vision Inspection Rollout", #date(2026, 10, 15), "Major", "Cameras installed", "R", null},
				            {"Vision Inspection Rollout", #date(2027, 1, 30), "Major", "Inspection live", "R", null},
				            {"Sensor Telemetry Rollout", #date(2026, 1, 10), "Minor", "Tag mapping complete", "R", null},
				            {"Sensor Telemetry Rollout", #date(2026, 4, 15), "Major", "Telemetry live", "R", null},
				            {"Sensor Telemetry Rollout", #date(2026, 8, 20), "Major", "Coverage target met", "R", null},
				            {"Edge Compute Buildout", #date(2026, 7, 1), "Minor", "Reference architecture", "R", null},
				            {"Edge Compute Buildout", #date(2026, 11, 15), "Major", "Edge nodes live", "R", null},
				            {"Robotics Cell Network", #date(2026, 11, 1), "Minor", "POC cell complete", "R", null},
				            {"Robotics Cell Network", #date(2027, 3, 1), "Major", "First cell migrated", "R", null},
				            {"Robotics Cell Network", #date(2027, 8, 15), "Major", "50% cells migrated", "R", null},
				            {"Robotics Cell Network", #date(2027, 12, 1), "Major", "All cells migrated", "R", null},
				            {"Plant Historian Migration", #date(2026, 5, 1), "Minor", "Plant 1 tag mapping", "R", null},
				            {"Plant Historian Migration", #date(2026, 11, 1), "Major", "Plant 1 cut over", "R", null},
				            {"Plant Historian Migration", #date(2027, 6, 1), "Major", "All plants migrated", "R", null},
				            {"Compact Series Redesign", #date(2026, 1, 25), "Minor", "Concept review", "R", null},
				            {"Compact Series Redesign", #date(2026, 3, 1), "Major", "Pilot production run", "R", null},
				            {"Compact Series Redesign", #date(2026, 5, 15), "Minor", "V2 spec released", "R", null},
				            {"Heavy-Duty Variant Launch", #date(2026, 5, 1), "Minor", "Prototype A complete", "R", null},
				            {"Heavy-Duty Variant Launch", #date(2026, 8, 5), "Major", "Launch approved", "R", null},
				            {"Sustainable Materials Program", #date(2026, 5, 20), "Minor", "Material spec frozen", "R", null},
				            {"Sustainable Materials Program", #date(2026, 7, 20), "Minor", "First test batch", "R", null},
				            {"Sustainable Materials Program", #date(2026, 12, 10), "Major", "Customer shipments begin", "R", null},
				            {"Sustainable Materials Program", #date(2027, 2, 28), "Major", "Adoption target met", "L", null},
				            {"CAD System Migration", #date(2026, 12, 15), "Minor", "Engineering pilot", "R", null},
				            {"CAD System Migration", #date(2027, 5, 1), "Major", "Org-wide rollout", "R", null},
				            {"ISO 9001 Recertification", #date(2026, 4, 1), "Minor", "Internal audit complete", "R", null},
				            {"ISO 9001 Recertification", #date(2026, 8, 1), "Minor", "External auditor on-site", "R", "Lead auditor: Mary Chen, KPMG. 4-day on-site engagement."},
				            {"ISO 9001 Recertification", #date(2026, 11, 15), "Major", "Certificate received", "R", "Certificate valid through November 2029 (3-year cycle)."},
				            {"Supplier Consolidation", #date(2026, 6, 1), "Minor", "Supplier list approved", "R", null},
				            {"Supplier Consolidation", #date(2026, 10, 1), "Major", "First 5 consolidated", "R", "First 5 consolidated: ~12% spend reduction realized in Q4."},
				            {"Supplier Consolidation", #date(2027, 1, 15), "Major", "Final wave complete", "R", null},
				            {"Fleet Refresh", #date(2027, 1, 15), "Minor", "PO approved", "R", null},
				            {"Fleet Refresh", #date(2027, 5, 1), "Major", "Fleet replacement complete", "R", null},
				            {"Procurement Workflow", #date(2026, 3, 15), "Minor", "Process designed", "R", null},
				            {"Procurement Workflow", #date(2026, 7, 1), "Major", "Pilot site live", "R", null},
				            {"Procurement Workflow", #date(2026, 11, 30), "Major", "Org-wide rollout", "R", null},
				            {"Safety Training Refresh", #date(2025, 12, 15), "Minor", "Curriculum approved", "R", null},
				            {"Safety Training Refresh", #date(2026, 6, 1), "Major", "100% completion", "R", null},
				            {"Business Continuity Program", #date(2026, 5, 1), "Minor", "Tabletop exercise", "R", null},
				            {"Business Continuity Program", #date(2026, 10, 1), "Major", "Plant failover test", "R", null},
				            {"Business Continuity Program", #date(2027, 1, 1), "Major", "Recertification complete", "L", null},
				            {"Plant Incident Response", #date(2026, 9, 1), "Minor", "v1 draft", "R", null},
				            {"Plant Incident Response", #date(2026, 12, 1), "Major", "v1 ratified", "R", "v1 ratified by ops council; rollout to all 3 plants begins Q1."},
				            {"Plant Incident Response", #date(2027, 3, 15), "Major", "Cross-plant drill", "R", null},
				            {"OT Network Segmentation", #date(2026, 3, 1), "Minor", "Baseline scan", "R", null},
				            {"OT Network Segmentation", #date(2026, 7, 15), "Major", "Plant 1 segmented", "R", "VLAN inventory complete; 47 firewall rule changes approved."},
				            {"OT Network Segmentation", #date(2026, 11, 1), "Minor", "Pentest engaged", "R", "External pentest firm: Praetorian Security; SOW signed."},
				            {"OT Network Segmentation", #date(2027, 5, 1), "Major", "All plants segmented", "R", null},
				            {"OT Network Segmentation", #date(2027, 11, 30), "Major", "Pentest pass", "R", null},
				            {"3PL Renegotiation", #date(2027, 1, 15), "Minor", "Initial terms", "R", null},
				            {"3PL Renegotiation", #date(2027, 5, 1), "Major", "Contracts signed", "R", null},
				            {"Warehouse Move", #date(2026, 1, 1), "__phantom", null, "none", null},
				            {"Inventory Audit Cycle", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Engineering Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Operations Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Finance Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Marketing Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Sales Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Quality Assurance Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Logistics Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Customer Success Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"HR Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Procurement Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"IT Infrastructure Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Compliance Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Research Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Field Services Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Training Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Facilities Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Security Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Legal Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Risk Management Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Analytics Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Strategy Initiative", #date(2026, 1, 1), "__phantom", null, "none", null},
                            {"Innovation Initiative", #date(2026, 1, 1), "__phantom", null, "none", null}
				        }
				    )
				
				    /*
				     * EXCEL SOURCE — uncomment to load from your own xlsx instead.
				     * Both Activities and Milestones sheets must follow the column
				     * schema documented in README.md.
				     *
				     *     RawSource = Excel.Workbook(File.Contents("YOUR_FILE_PATH\\Demo-Roadmap-Source.xlsx"), null, true),
				     *     Sheet = RawSource{[Item="Milestones",Kind="Sheet"]}[Data],
				     *     PromotedHeaders = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				     *     Source = Table.TransformColumnTypes(PromotedHeaders,{
				     *         {"Activity", type text},
				     *         {"Milestone Date", type date},
				     *         {"Milestone Type", type text},
				     *         {"Milestone Label", type text},
				     *         {"Label Position", type text},
				     *         {"Milestone Note", type text}
				     *     })
				     */
				in
				    Source

	annotation PBI_ResultType = Table

